# Ultralytics YOLO 🚀, AGPL-3.0 license

task: detect  # YOLO task (detect, segment, classify, pose)
mode: train  # YOLO mode (train, val, predict, export)

# Train settings
model: D:\Work\codev2\code\work_code\model_code\yolov8x.pt  # path to model file
data: D:\Work\codev2\code\train_data_2\YOLODataset\dataset.yaml # path to data file
epochs: 15 # number of epochs to train for
batch: 1 # number of images per batch (-1 for AutoBatch)
imgsz: 1337  # input images size as int for train and val modes
device: 0  # device to run on (cuda device=0 or device=cpu)
workers: 3  # number of worker threads for data loading
project: yolo_project  # project name
name: experiment  # experiment name, results saved to 'project/name' directory
pretrained: True  # whether to use a pretrained model
cache: disk # cache results in memory for faster training
# Hyperparameters
lr0: 0.02  # initial learning rate
lrf: 0.02  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4
warmup_epochs: 3.0  # warmup epochs
warmup_momentum: 0.8  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr

# Augmentation settings
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.5  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.0  # image mosaic (probability)
mixup: 0.0  # image mixup (probability)

# Val/Test settings
val: True  # validate/test during training
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image

# Saving settings
save: True  # save train checkpoints and predict results
save_period: -1  # Save checkpoint every x epochs (disabled if < 1)

# Other settings
verbose: True  # whether to print verbose output
seed: 0  # random seed for reproducibility
deterministic: True  # whether to enable deterministic mode

# Optimizer
optimizer: auto  # optimizer (auto, SGD, Adam, AdamW, RMSProp)

# Learning rate scheduler
cos_lr: False  # use cosine learning rate scheduler

# Advanced
amp: True  # Automatic Mixed Precision (AMP) training